# - nvim
# - ZSH
# - Get my dotfiles
# - Need Oh My ZSH
# - Add all git repos that I want for projects
# - Install github CLI
# - Add more to your playbook as you add more tools
- name: Install all the packages I need for development
  hosts: all
  connection: local
  gather_facts: true
  vars:
      is_linux:  "{{ true if ansible_pkg_mgr != 'brew' else false }}"
  tasks:
      - name: Provision linux environment
        include_role:
            name: provision_linux
        when: is_linux
